version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    image: node:20-bookworm
    working_dir: /app
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - ./app:/app            # <= <-- this was the missing value
    command: ["node","index.js"]
